### ISSUE TITLE
Add more dimensions to the distcopy stats

### ISSUE THREAD

**Issue by etorreborre** [ambiata/notion#87]
When this can be retrieved from the instance metadata as <account>.<client>.<env>.

Since notion is open-source and not Ambiata-only we can leave open the possibility to add arbitrary dimensions for `distcopy` and provide a default implementation which splits the instance role on `.` and take each component as a dimension.

**Comment by markhibberd** [comment]
@etorreborre I don't understand this one, can you run it past me this week sometime.

**Comment by etorreborre** [comment]
@markhibberd sorry, the specific issue is that `live` and `staging` stats are not being distinguished.

**Comment by etorreborre** [comment]
Closing this. It is better to let client applications publish the stats themselves using exsum.scala.
