### ISSUE TITLE
Remove the CloudWatch code

### ISSUE THREAD

**Issue by etorreborre** [ambiata/notion#88]
It will be subsumed by applications using exsum.scala to publish stats themselves. Possibly a `DistCopyStats => ExsumData` function would be useful there.

**Comment by nhibberd** [comment]
What about ivory support (not that it is current used)

**Comment by etorreborre** [comment]
Same answer, use exsum.scala? One advantage comes from the possibility to store stats in S3 if we want long-term analysis and not just alarms.

**Comment by markhibberd** [comment]
Can we discuss this again before anything is removed. I want to make sure the global counts are still available. They are proving pretty useful.
